# Source/Core/DolphinQt/HotkeyScheduler.cpp

[allow_freelook_hotkey_message]
match = '''
      const bool hardcore = AchievementManager::GetInstance().IsHardcoreModeActive();
      if (hardcore)
        OSD::AddMessage("Free Look is Disabled in Hardcore Mode");
      else
        OSD::AddMessage(fmt::format("Free Look: {}", new_value ? "Enabled" : "Disabled"));
'''
rewrite = '''
      // [PATCH] raunlock: allow free look in hardcore mode
      OSD::AddMessage(fmt::format("Free Look: {}", new_value ? "Enabled" : "Disabled"));
'''

[allow_speed_display_always]
match = '''
      auto ShowEmulationSpeed = [] {
        const float emulation_speed = Config::Get(Config::MAIN_EMULATION_SPEED);
        if (!AchievementManager::GetInstance().IsHardcoreModeActive() ||
            Config::Get(Config::MAIN_EMULATION_SPEED) >= 1.0f ||
            Config::Get(Config::MAIN_EMULATION_SPEED) <= 0.0f)
        {
          OSD::AddMessage(emulation_speed <= 0 ? "Speed Limit: Unlimited" :
                                                 fmt::format("Speed Limit: {}%",
                                                             std::lround(emulation_speed * 100.f)));
        }
      };
'''
rewrite = '''
      auto ShowEmulationSpeed = [] {
        const float emulation_speed = Config::Get(Config::MAIN_EMULATION_SPEED);
        // [PATCH] raunlock: always show speed limit message
        OSD::AddMessage(emulation_speed <= 0 ? "Speed Limit: Unlimited" :
                                               fmt::format("Speed Limit: {}%",
                                                           std::lround(emulation_speed * 100.f)));
      };
'''
