# cheat_manager.c

[skip_pause_cheevos_on_apply_cheats]
match = '''
#ifdef HAVE_CHEEVOS
   if (idx != 0 && rcheevos_hardcore_active())
      cheat_manager_pause_cheevos();
#endif
}
'''
rewrite = '''
   // [PATCH] unblockh: removed hardcore pause when applying EMU-handler cheats
}
'''

[skip_pause_cheevos_on_retro_apply]
match = '''
#ifdef HAVE_CHEEVOS
   if (cheat_applied && rcheevos_hardcore_active())
      cheat_manager_pause_cheevos();
#endif
}
'''
rewrite = '''
   // [PATCH] unblockh: removed hardcore pause when applying RETRO-handler cheats
}
'''
