# command.c

[block_post_state_loaded]
match = '''
#ifdef HAVE_CHEEVOS
   if (rcheevos_hardcore_active())
   {
      const char *_msg = msg_hash_to_str(MSG_CHEEVOS_HARDCORE_MODE_DISABLED);
      rcheevos_pause_hardcore();
      runloop_msg_queue_push(_msg, strlen(_msg), 0, 180, true, NULL,
            MESSAGE_QUEUE_ICON_DEFAULT, MESSAGE_QUEUE_CATEGORY_INFO);
   }
#endif
#ifdef HAVE_NETWORKING
   netplay_driver_ctl(RARCH_NETPLAY_CTL_LOAD_SAVESTATE, NULL);
'''
rewrite = '''
   // [PATCH] raunlock: allow post-state-loaded in hardcore mode
#ifdef HAVE_NETWORKING
   netplay_driver_ctl(RARCH_NETPLAY_CTL_LOAD_SAVESTATE, NULL);
'''

[block_movie_seek_hardcore_check]
match = '''
#ifdef HAVE_CHEEVOS
   ret = !rcheevos_hardcore_active();
#endif
   if (ret)
      ret = movie_seek_to_frame(input_st, frame);
'''
rewrite = '''
   // [PATCH] raunlock: allow movie seek command in hardcore mode
   if (ret)
      ret = movie_seek_to_frame(input_st, frame);
'''

[block_write_core_ram]
match = '''
   if (rcheevos_hardcore_active())
   {
      RARCH_LOG("[Command] Achievements hardcore mode disabled by WRITE_CORE_RAM.\n");
      rcheevos_pause_hardcore();
   }

   while (*arg)
'''
rewrite = '''
   // [PATCH] raunlock: allow WRITE_CORE_RAM in hardcore mode

   while (*arg)
'''

[block_write_core_memory]
match = '''
#ifdef HAVE_CHEEVOS
      if (rcheevos_hardcore_active())
      {
         RARCH_LOG("[Command] Achievements hardcore mode disabled by WRITE_CORE_MEMORY.\n");
         rcheevos_pause_hardcore();
      }
#endif
   }

   cmd->replier(cmd, reply, strlen(reply));
'''
rewrite = '''
      // [PATCH] raunlock: allow WRITE_CORE_MEMORY in hardcore mode
   }

   cmd->replier(cmd, reply, strlen(reply));
'''

[block_load_entry_state]
match = '''
#ifdef HAVE_CHEEVOS
   if (rcheevos_hardcore_active())
      return false;
#endif
#ifdef HAVE_NETWORKING
   if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_ENABLED, NULL))
      return false;
#endif

   if (!runloop_get_entry_state_path(
'''
rewrite = '''
   // [PATCH] raunlock: allow entry state load in hardcore mode
#ifdef HAVE_NETWORKING
   if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_ENABLED, NULL))
      return false;
#endif

   if (!runloop_get_entry_state_path(
'''

[block_load_auto_state]
match = '''
#ifdef HAVE_CHEEVOS
   if (rcheevos_hardcore_active())
      return false;
#endif
#ifdef HAVE_NETWORKING
   if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_ENABLED, NULL))
      return false;
#endif

   _len = strlcpy(savestate_name_auto, name_savestate,
'''
rewrite = '''
   // [PATCH] raunlock: allow auto state load in hardcore mode
#ifdef HAVE_NETWORKING
   if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_ENABLED, NULL))
      return false;
#endif

   _len = strlcpy(savestate_name_auto, name_savestate,
'''
