# runloop.c

[block_pause_and_frameadvance]
match = '''
#ifdef HAVE_CHEEVOS
      if (cheevos_hardcore_active)
      {
         if (!(runloop_st->flags & RUNLOOP_FLAG_PAUSED))
         {
            /* In hardcore mode, the user is only allowed to pause infrequently. */
            if ((pause_pressed && !old_pause_pressed) ||
               (!focused && old_focus && pause_nonactive))
            {
               /* If the user is trying to pause, check to see if it's allowed. */
               if (!rcheevos_is_pause_allowed())
               {
                  pause_pressed = false;
                  if (pause_nonactive)
                     focused = true;
               }
            }
         }
      }
      else /* frame advance not allowed in hardcore */
#endif
      {
         frameadvance_pressed = BIT256_GET(current_bits, RARCH_FRAMEADVANCE);
'''
rewrite = '''
// [PATCH] unblockh: allow pause and frame advance in hardcore mode
      {
         frameadvance_pressed = BIT256_GET(current_bits, RARCH_FRAMEADVANCE);
'''

[block_unpause_on_frameadvance]
match = '''
#ifdef HAVE_CHEEVOS
         else if (!cheevos_hardcore_active)
#else
         else
#endif
            runloop_paused = false;
'''
rewrite = '''
         else
            runloop_paused = false;
'''

[block_slowmotion]
match = '''
#ifdef HAVE_CHEEVOS
   if (!cheevos_hardcore_active)
#endif
   {
      {
         /* Check slowmotion hotkeys */
'''
rewrite = '''
   // [PATCH] unblockh: allow slowmotion in hardcore mode
   {
      {
         /* Check slowmotion hotkeys */
'''

[block_auto_load_state]
match = '''
#ifdef HAVE_CHEEVOS
   if (     !cheevos_enable
         || !cheevos_hardcore_mode_enable)
#endif
   {
#ifdef HAVE_BSV_MOVIE
'''
rewrite = '''
   // [PATCH] unblockh: allow auto load state in hardcore mode
   {
#ifdef HAVE_BSV_MOVIE
'''
