# tasks/task_save.c

[cancel_task_on_hardcore]
match = '''
#ifdef HAVE_CHEEVOS
   if (rcheevos_hardcore_active())
      task_set_flags(task, RETRO_TASK_FLG_CANCELLED, true);
#endif
'''
rewrite = '''
// [PATCH] unblockh: allow save state tasks in hardcore mode
'''

[goto_error_on_hardcore]
match = '''
#ifdef HAVE_CHEEVOS
   if (rcheevos_hardcore_active())
      goto error;
#endif
'''
rewrite = '''
// [PATCH] unblockh: allow state loading in hardcore mode
'''
