# src/core/settings.cpp

[allow_rewind_and_speed]
match = '''
  // if challenge mode is enabled, disable things like rewind since they use save states
  if (Achievements::IsHardcoreModeActive())
  {
    :[_]
  }
'''
rewrite = '''
  // [PATCH] unblockh: allow rewind and speed changes in hardcore mode
'''
