# src/core/system.cpp

[allow_load_state_in_hardcore]
match = '''
std::optional<bool> System::LoadState(const char* path, Error* error, bool save_undo_state, bool force_update_display)
{
  if (!IsValid() || IsReplayingGPUDump())
  {
    Error::SetStringView(error, TRANSLATE_SV("System", "System is not in correct state."));
    return false;
  }

  if (Achievements::IsHardcoreModeActive())
  {
    Achievements::ConfirmHardcoreModeDisableAsync(
      TRANSLATE("Achievements", "Loading state"),
      [path = std::string(path), save_undo_state, force_update_display](bool approved) {
        if (approved)
          LoadState(path.c_str(), nullptr, save_undo_state, force_update_display);
      });
    return std::nullopt;
  }

  FlushSaveStates();
'''
rewrite = '''
std::optional<bool> System::LoadState(const char* path, Error* error, bool save_undo_state, bool force_update_display)
{
  if (!IsValid() || IsReplayingGPUDump())
  {
    Error::SetStringView(error, TRANSLATE_SV("System", "System is not in correct state."));
    return false;
  }

  // [PATCH] unblockh: load state directly without disabling hardcore mode
  FlushSaveStates();
'''

[allow_boot_with_save_state_in_hardcore]
match = '''
    if ((!parameters.save_state.empty() || !exe_override.empty()) && Achievements::IsHardcoreModeActive())
    {
      :[_]

      // Technically a failure, but user-initiated. Returning false here would try to display a non-existent error.
      Host::OnSystemStopping();
      DestroySystem();
      return true;
    }
'''
rewrite = '''
    // [PATCH] unblockh: allow booting with save state or exe override in hardcore mode
'''

[allow_frame_step_in_hardcore]
match = '''
  if (Achievements::IsHardcoreModeActive())
  {
    Achievements::ConfirmHardcoreModeDisableAsync("Frame stepping", [](bool approved) {
      if (approved)
        FrameStep();
    });
    return;
  }

  s_state.frame_step_request = true;
'''
rewrite = '''
  // [PATCH] unblockh: allow frame stepping in hardcore mode
  s_state.frame_step_request = true;
'''

[allow_undo_load_state_in_hardcore]
match = '''
  if (Achievements::IsHardcoreModeActive())
  {
    Achievements::ConfirmHardcoreModeDisableAsync(TRANSLATE_SV("System", "Undo load state"), [](bool result) {
      if (result)
        Host::RunOnCoreThread(&System::UndoLoadState);
    });
    return;
  }

  std::string osd_key = "UndoLoadState";
'''
rewrite = '''
  // [PATCH] unblockh: allow undo load state in hardcore mode
  std::string osd_key = "UndoLoadState";
'''
