# pcsx2/ImGui/FullscreenUI.cpp

[allow_load_state_in_pause_menu]
match = '''
				const bool can_load_state = s_current_disc_crc != 0 && !Achievements::IsHardcoreModeActive();
'''
rewrite = '''
				// [PATCH] raunlock: allow load state in hardcore mode
				const bool can_load_state = s_current_disc_crc != 0;
'''

[allow_load_state_in_save_state_selector]
match = '''
					false, is_loading ? !Achievements::IsHardcoreModeActive() : true, LAYOUT_MENU_BUTTON_HEIGHT_NO_SUMMARY))
'''
rewrite = '''
					false, true, LAYOUT_MENU_BUTTON_HEIGHT_NO_SUMMARY))
'''
